DROP DATABASE IF EXISTS CyberMafia;
CREATE DATABASE CyberMafia;
USE CyberMafia;

CREATE TABLE User(
UserName VARCHAR(20),
Password VARCHAR(256),
Salt VARCHAR(256),
Email VARCHAR(256),
LastLogin datetime,
CONSTRAINT UserName_PK
PRIMARY KEY (UserName)
);

CREATE TABLE PC_CPU(
ID INT AUTO_INCREMENT UNIQUE NOT NULL,
Name CHAR(20),
GHz FLOAT,
CONSTRAINT ID_CPU_PK
PRIMARY KEY (ID)
);

CREATE TABLE PC_GPU(
ID INT AUTO_INCREMENT UNIQUE NOT NULL,
Name CHAR(20),
GHz FLOAT,
CONSTRAINT ID_GPU_PK
PRIMARY KEY (ID)
);

CREATE TABLE PC_HDD(
ID INT AUTO_INCREMENT UNIQUE NOT NULL,
Name CHAR(20),
Size BIGINT
);


CREATE TABLE FireWall(
ID INT AUTO_INCREMENT NOT NULL,
Name CHAR(20),
Security INT,
CONSTRAINT FW_ID_PK
PRIMARY KEY (ID)
);

CREATE TABLE Backdoor(
ID INT AUTO_INCREMENT NOT NULL,
Name CHAR(20),
Power INT,
CONSTRAINT BD_ID_PK
PRIMARY KEY (ID)
);

CREATE TABLE Player(
UserName VARCHAR(20),
playerIP CHAR(19), 
pc_CPU_ID INT, 
pc_GPU_ID INT, 
pc_HDD_ID INT,
FireWall INT,
BackDoor INT,
CONSTRAINT Username_PK
PRIMARY KEY (userName),
CONSTRAINT Username_FK
FOREIGN KEY (UserName) REFERENCES User(UserName),
CONSTRAINT pc_CPU_ID_FK
FOREIGN KEY (pc_CPU_ID) REFERENCES PC_CPU(ID),
CONSTRAINT pc_GPU_ID_FK
FOREIGN KEY (pc_GPU_ID) REFERENCES PC_GPU(ID),
CONSTRAINT pc_HDD_ID_FK
FOREIGN KEY (pc_HDD_ID) REFERENCES PC_HDD(ID),
CONSTRAINT FW_ID_FK
FOREIGN KEY (FireWall) REFERENCES FireWall(ID),
CONSTRAINT BD_ID_FK
FOREIGN KEY (BackDoor) REFERENCES Backdoor(ID)
);

CREATE TABLE NPC(
ID INT AUTO_INCREMENT NOT NULL,
Name CHAR(20),
IP CHAR(19),
-- Type
CONSTRAINT Name_PK
PRIMARY KEY (ID)
);

CREATE TABLE IP_List (
    IP CHAR(19),
    UserName VARCHAR(20),
    NPCID INT,
    CONSTRAINT IP_PK PRIMARY KEY (IP),
    CONSTRAINT IPLIST_UserName_FK FOREIGN KEY (UserName)
        REFERENCES Player (UserName),
    CONSTRAINT NPCID_FK FOREIGN KEY (NPCID)
        REFERENCES NPC (ID)
);
